In [2]:
#imports
import pandas as pd
import numpy as np
import optuna
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve

## Read in adult census data and perform data preprocessing

In [3]:
# importing the data
adult = pd.read_csv('/Users/donyabehroozi/Documents/gsb545/GSB-545/In Class Assignments/adult.csv')
adult.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [4]:
#data preprocessing

# replace ? with np.nan
adult = adult.replace("?", np.nan)
adult.head()

# convert target variable to binary
adult["income"] = adult["income"].apply(lambda x: 1 if x == ">50K" else 0)

# convert gender to 0/1 (doesn't need categorical encoding since it's binary)
if "gender" in adult.columns:
    adult["gender"] = adult["gender"].apply(lambda x: 1 if x == "Male" else 0)

# drop the fnlwgt variable as it is not useful for modeling
adult.drop(columns=["fnlwgt"], inplace=True)  
    
adult.head(20)

,age,workclass,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,1,0,0,40,United-States,0
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,1,0,0,50,United-States,0
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,1,0,0,40,United-States,1
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,1,7688,0,40,United-States,1
4,18,NaN,Some-college,10,Never-married,NaN,Own-child,White,0,0,0,30,United-States,0
5,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,1,0,0,30,United-States,0
6,29,NaN,HS-grad,9,Never-married,NaN,Unmarried,Black,1,0,0,40,United-States,0
7,63,Self-emp-not-inc,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,1,3103,0,32,United-States,1
8,24,Private,Some-college,10,Never-married,Other-service,Unmarried,White,0,0,0,40,United-States,0
9,55,Private,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,1,0,0,10,United-States,0
10,65,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,1,6418,0,40,United-States,1
11,36,Federal-gov,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,1,0,0,40,United-States,0
12,26,Private,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,0,0,0,39,United-States,0
13,58,NaN,HS-grad,9,Married-civ-spouse,NaN,Husband,White,1,0,0,35,United-States,0
14,48,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,1,3103,0,48,United-States,1
15,43,Private,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,50,United-States,1
16,20,State-gov,Some-college,10,Never-married,Other-service,Own-child,White,1,0,0,25,United-States,0
17,43,Private,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,0,0,0,30,United-States,0
18,37,Private,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,White,0,0,0,20,United-States,0
19,40,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,1,0,0,45,NaN,1

In [5]:
#feature engineering

#net capital activity
adult['capital_net'] = adult['capital-gain'] - adult['capital-loss'] 

#age and education interaction
adult['age_education_interaction'] = adult['age'] * adult['educational-num']

#log transformation of net capital activity to help models handle extreme values
capital_net_clipped = adult['capital_net'].clip(lower=0)
adult['capital_net_log'] = np.log1p(capital_net_clipped)

#age and marriage interaction
adult['age_married'] = adult['age'] * (adult['marital-status'] == 'Married-civ-spouse').astype(int)

adult.head()

,age,workclass,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,capital_net,age_education_interaction,capital_net_log,age_married
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,1,0,0,40,United-States,0,0,175,0.000000,0
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,1,0,0,50,United-States,0,0,342,0.000000,38
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,1,0,0,40,United-States,1,0,336,0.000000,28
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,1,7688,0,40,United-States,1,7688,440,8.947546,44
4,18,NaN,Some-college,10,Never-married,NaN,Own-child,White,0,0,0,30,United-States,0,0,180,0.000000,0

In [17]:
#count NAs
adult.isna().sum()

age                             0
workclass                    2799
education                       0
educational-num                 0
marital-status                  0
occupation                   2809
relationship                    0
race                            0
gender                          0
capital-gain                    0
capital-loss                    0
hours-per-week                  0
native-country                857
income                          0
capital_net                     0
age_education_interaction       0
capital_net_log                 0
age_married                     0
dtype: int64

In [6]:
#impute missing values with "unknown"
for col in ['workclass', 'occupation', 'native-country']:
    adult[col] = adult[col].fillna('Unknown')

adult.head(20)

,age,workclass,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income,capital_net,age_education_interaction,capital_net_log,age_married
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,1,0,0,40,United-States,0,0,175,0.000000,0
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,1,0,0,50,United-States,0,0,342,0.000000,38
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,1,0,0,40,United-States,1,0,336,0.000000,28
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,1,7688,0,40,United-States,1,7688,440,8.947546,44
4,18,Unknown,Some-college,10,Never-married,Unknown,Own-child,White,0,0,0,30,United-States,0,0,180,0.000000,0
5,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,1,0,0,30,United-States,0,0,204,0.000000,0
6,29,Unknown,HS-grad,9,Never-married,Unknown,Unmarried,Black,1,0,0,40,United-States,0,0,261,0.000000,0
7,63,Self-emp-not-inc,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,1,3103,0,32,United-States,1,3103,945,8.040447,63
8,24,Private,Some-college,10,Never-married,Other-service,Unmarried,White,0,0,0,40,United-States,0,0,240,0.000000,0
9,55,Private,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,1,0,0,10,United-States,0,0,220,0.000000,55
10,65,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,1,6418,0,40,United-States,1,6418,585,8.767018,65
11,36,Federal-gov,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,1,0,0,40,United-States,0,0,468,0.000000,36
12,26,Private,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,0,0,0,39,United-States,0,0,234,0.000000,0
13,58,Unknown,HS-grad,9,Married-civ-spouse,Unknown,Husband,White,1,0,0,35,United-States,0,0,522,0.000000,58
14,48,Private,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,1,3103,0,48,United-States,1,3103,432,8.040447,48
15,43,Private,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,1,0,0,50,United-States,1,0,602,0.000000,43
16,20,State-gov,Some-college,10,Never-married,Other-service,Own-child,White,1,0,0,25,United-States,0,0,200,0.000000,0
17,43,Private,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,0,0,0,30,United-States,0,0,387,0.000000,43
18,37,Private,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,White,0,0,0,20,United-States,0,0,333,0.000000,0
19,40,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,1,0,0,45,Unknown,1,0,640,0.000000,40

In [7]:
# defining X
num_cols = ['age', 'educational-num', 'capital-gain', 'capital-loss',
            'hours-per-week', 'capital_net', 'capital_net_log', 
            'age_education_interaction', 'age_married']

cat_cols = ['workclass', 'education', 'marital-status',
            'occupation', 'relationship', 'race', 'native-country']

X = pd.concat([
    adult[num_cols],
    pd.get_dummies(adult[cat_cols], drop_first=True).astype(int)
], axis=1)

# defining y
y = adult['income'].to_numpy() 

# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.2, random_state=321)

# scale numeric columns only
min_max_scaler = MinMaxScaler()
X_train[num_cols] = min_max_scaler.fit_transform(X_train[num_cols])
X_test[num_cols] = min_max_scaler.transform(X_test[num_cols])

print(X_train.head())
print(y_train[:5])

            age  educational-num  capital-gain  capital-loss  hours-per-week  \
48353  0.027397         0.533333           0.0      0.000000        0.397959
8310   0.301370         0.666667           0.0      0.000000        0.500000
6063   0.287671         0.733333           0.0      0.000000        0.377551
8229   0.068493         0.333333           0.0      0.000000        0.397959
20762  0.109589         0.800000           0.0      0.399679        0.397959

       capital_net  capital_net_log  age_education_interaction  age_married  \
48353     0.041742              0.0                   0.114200          0.0
8310      0.041742              0.0                   0.308039          0.0
6063      0.041742              0.0                   0.328325          0.0
8229      0.041742              0.0                   0.084899          0.0
20762     0.025059              0.0                   0.229902          0.0

       workclass_Local-gov  ...  native-country_Puerto-Rico  \
48353                    0  ...                           0
8310                     0  ...                           0
6063                     0  ...                           0
8229                     0  ...                           0
20762                    0  ...                           0

       native-country_Scotland  native-country_South  native-country_Taiwan  \
48353                        0                     0                      0
8310                         0                     0                      0
6063                         0                     0                      0
8229                         0                     0                      0
20762                        0                     0                      0

       native-country_Thailand  native-country_Trinadad&Tobago  \
48353                        0                               0
8310                         0                               0
6063                         1                               0
8229                         0                               0
20762                        0                               0

       native-country_United-States  native-country_Unknown  \
48353                             1                       0
8310                              1                       0
6063                              0                       0
8229                              1                       0
20762                             1                       0

       native-country_Vietnam  native-country_Yugoslavia
48353                       0                          0
8310                        0                          0
6063                        0                          0
8229                        0                          0
20762                       0                          0

[5 rows x 102 columns]
[0 0 0 0 0]

## Baseline neural network (Funnel architecture, 2 hidden layers, 64 -> 32 -> 1)

In [8]:
#set random seed
tf.random.set_seed(321)

In [21]:
#construct the model
inputs = keras.Input(shape=(102,)) #102 inputs, input layer
x = layers.Dense(64, activation='relu')(inputs) #hidden layer 1
x = layers.Dense(32, activation='relu')(x) #hidden layer 2
outputs = layers.Dense(1, activation='sigmoid')(x) #output layer (sigmoid for binary outcome)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_model")

In [22]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 539us/step - auc: 0.8803 - loss: 0.3550 - val_auc: 0.8952 - val_loss: 0.3349
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - auc: 0.9021 - loss: 0.3249 - val_auc: 0.8993 - val_loss: 0.3282
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 413us/step - auc: 0.9067 - loss: 0.3177 - val_auc: 0.9020 - val_loss: 0.3242
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - auc: 0.9103 - loss: 0.3118 - val_auc: 0.9037 - val_loss: 0.3217
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - auc: 0.9133 - loss: 0.3069 - val_auc: 0.9049 - val_loss: 0.3200
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - auc: 0.9158 - loss: 0.3027 - val_auc: 0.9059 - val_loss: 0.3190
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - auc: 0.9179 - loss: 0.2992 - val_auc: 0.9066 - val_loss: 0.3187
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - auc: 0.9196 - loss: 0.2962 - val_auc: 0.9064 - val_loss: 0.3197
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - auc: 0.9211 - loss: 0.2935 - val_auc: 0.9063 - val_loss: 0.3203
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 361us/step - auc: 0.9225 - loss: 0.2910 - val_auc: 0.9060 - val_loss: 0.3210
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 356us/step - auc: 0.9237 - loss: 0.2888 - val_auc: 0.9058 - val_loss: 0.3219
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - auc: 0.9248 - loss: 0.2867 - val_auc: 0.9056 - val_loss: 0.3229
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - auc: 0.9258 - loss: 0.2848 - val_auc: 0.9046 - val_loss: 0.3246
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - auc: 0.9267 - loss: 0.2832 - val_auc: 0.9043 - val_loss: 0.3252
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - auc: 0.9276 - loss: 0.2815 - val_auc: 0.9039 - val_loss: 0.3268
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - auc: 0.9284 - loss: 0.2798 - val_auc: 0.9035 - val_loss: 0.3288
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9293 - loss: 0.2782 - val_auc: 0.9032 - val_loss: 0.3303
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 400us/step - auc: 0.9301 - loss: 0.2767 - val_auc: 0.9027 - val_loss: 0.3325
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9308 - loss: 0.2752 - val_auc: 0.9020 - val_loss: 0.3348
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9315 - loss: 0.2740 - val_auc: 0.9016 - val_loss: 0.3365
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 245us/step - auc: 0.9004 - loss: 0.3385

In [23]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 205us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.9007

# Experiment 1: Architecture change

## Flat architecture (102 -> 64 -> 64 -> 1)

In [24]:
inputs = keras.Input(shape=(102,))
x = layers.Dense(64, activation='relu')(inputs)  # hidden layer 1
x = layers.Dense(64, activation='relu')(x)        # hidden layer 2
outputs = layers.Dense(1, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_flat")

In [25]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 454us/step - auc: 0.8834 - loss: 0.3510 - val_auc: 0.8961 - val_loss: 0.3337
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 382us/step - auc: 0.9027 - loss: 0.3243 - val_auc: 0.8996 - val_loss: 0.3282
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - auc: 0.9069 - loss: 0.3177 - val_auc: 0.9023 - val_loss: 0.3244
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - auc: 0.9100 - loss: 0.3124 - val_auc: 0.9040 - val_loss: 0.3216
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9128 - loss: 0.3078 - val_auc: 0.9049 - val_loss: 0.3206
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - auc: 0.9152 - loss: 0.3038 - val_auc: 0.9061 - val_loss: 0.3196
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - auc: 0.9173 - loss: 0.3004 - val_auc: 0.9067 - val_loss: 0.3186
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - auc: 0.9192 - loss: 0.2971 - val_auc: 0.9066 - val_loss: 0.3191
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - auc: 0.9209 - loss: 0.2940 - val_auc: 0.9064 - val_loss: 0.3198
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - auc: 0.9224 - loss: 0.2913 - val_auc: 0.9060 - val_loss: 0.3212
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - auc: 0.9238 - loss: 0.2889 - val_auc: 0.9058 - val_loss: 0.3226
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - auc: 0.9250 - loss: 0.2866 - val_auc: 0.9054 - val_loss: 0.3238
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 367us/step - auc: 0.9262 - loss: 0.2844 - val_auc: 0.9050 - val_loss: 0.3259
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - auc: 0.9273 - loss: 0.2825 - val_auc: 0.9043 - val_loss: 0.3280
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - auc: 0.9284 - loss: 0.2805 - val_auc: 0.9036 - val_loss: 0.3303
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - auc: 0.9292 - loss: 0.2788 - val_auc: 0.9032 - val_loss: 0.3329
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - auc: 0.9301 - loss: 0.2770 - val_auc: 0.9027 - val_loss: 0.3358
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 398us/step - auc: 0.9310 - loss: 0.2753 - val_auc: 0.9024 - val_loss: 0.3381
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - auc: 0.9318 - loss: 0.2738 - val_auc: 0.9016 - val_loss: 0.3415
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 362us/step - auc: 0.9326 - loss: 0.2721 - val_auc: 0.9011 - val_loss: 0.3436
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 247us/step - auc: 0.8999 - loss: 0.3406

In [26]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.9006

## Expanding architecture (102 -> 32 -> 64 -> 1)

In [27]:
inputs = keras.Input(shape=(102,))
x = layers.Dense(32, activation='relu')(inputs)  
x = layers.Dense(64, activation='relu')(x)       
outputs = layers.Dense(1, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_expanding")

In [28]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 473us/step - auc: 0.8798 - loss: 0.3554 - val_auc: 0.8950 - val_loss: 0.3353
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - auc: 0.9016 - loss: 0.3261 - val_auc: 0.8992 - val_loss: 0.3292
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 470us/step - auc: 0.9059 - loss: 0.3193 - val_auc: 0.9021 - val_loss: 0.3247
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - auc: 0.9092 - loss: 0.3140 - val_auc: 0.9041 - val_loss: 0.3216
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step - auc: 0.9117 - loss: 0.3098 - val_auc: 0.9053 - val_loss: 0.3192
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - auc: 0.9137 - loss: 0.3065 - val_auc: 0.9064 - val_loss: 0.3177
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - auc: 0.9154 - loss: 0.3035 - val_auc: 0.9065 - val_loss: 0.3172
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - auc: 0.9169 - loss: 0.3011 - val_auc: 0.9068 - val_loss: 0.3169
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - auc: 0.9181 - loss: 0.2990 - val_auc: 0.9071 - val_loss: 0.3167
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - auc: 0.9193 - loss: 0.2969 - val_auc: 0.9071 - val_loss: 0.3165
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - auc: 0.9204 - loss: 0.2950 - val_auc: 0.9070 - val_loss: 0.3170
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 356us/step - auc: 0.9212 - loss: 0.2936 - val_auc: 0.9069 - val_loss: 0.3174
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step - auc: 0.9221 - loss: 0.2921 - val_auc: 0.9071 - val_loss: 0.3177
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - auc: 0.9230 - loss: 0.2905 - val_auc: 0.9069 - val_loss: 0.3184
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - auc: 0.9238 - loss: 0.2891 - val_auc: 0.9063 - val_loss: 0.3198
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - auc: 0.9243 - loss: 0.2881 - val_auc: 0.9064 - val_loss: 0.3205
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9249 - loss: 0.2868 - val_auc: 0.9061 - val_loss: 0.3205
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - auc: 0.9256 - loss: 0.2856 - val_auc: 0.9052 - val_loss: 0.3229
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - auc: 0.9262 - loss: 0.2845 - val_auc: 0.9046 - val_loss: 0.3247
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 379us/step - auc: 0.9267 - loss: 0.2835 - val_auc: 0.9043 - val_loss: 0.3256
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 242us/step - auc: 0.9053 - loss: 0.3242

In [29]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 205us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.9054

# Experiment 2: Different number of layers

## Single hidden layer

In [ ]:
#construct the model
inputs = keras.Input(shape=(102,)) #102 inputs, input layer
x = layers.Dense(64, activation='relu')(inputs) #hidden layer 1
outputs = layers.Dense(1, activation='sigmoid')(x) #output layer (sigmoid for binary outcome)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_model_sl")

In [31]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 445us/step - auc: 0.8763 - loss: 0.3601 - val_auc: 0.8936 - val_loss: 0.3374
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 339us/step - auc: 0.9006 - loss: 0.3273 - val_auc: 0.8971 - val_loss: 0.3320
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 337us/step - auc: 0.9039 - loss: 0.3222 - val_auc: 0.8994 - val_loss: 0.3283
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 337us/step - auc: 0.9063 - loss: 0.3183 - val_auc: 0.9013 - val_loss: 0.3255
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - auc: 0.9084 - loss: 0.3149 - val_auc: 0.9027 - val_loss: 0.3234
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - auc: 0.9102 - loss: 0.3121 - val_auc: 0.9037 - val_loss: 0.3218
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 336us/step - auc: 0.9119 - loss: 0.3094 - val_auc: 0.9046 - val_loss: 0.3203
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 339us/step - auc: 0.9133 - loss: 0.3071 - val_auc: 0.9056 - val_loss: 0.3189
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - auc: 0.9147 - loss: 0.3049 - val_auc: 0.9062 - val_loss: 0.3179
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 336us/step - auc: 0.9159 - loss: 0.3029 - val_auc: 0.9067 - val_loss: 0.3170
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 333us/step - auc: 0.9170 - loss: 0.3011 - val_auc: 0.9070 - val_loss: 0.3165
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 334us/step - auc: 0.9179 - loss: 0.2996 - val_auc: 0.9074 - val_loss: 0.3160
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 338us/step - auc: 0.9188 - loss: 0.2982 - val_auc: 0.9077 - val_loss: 0.3155
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 336us/step - auc: 0.9196 - loss: 0.2968 - val_auc: 0.9079 - val_loss: 0.3152
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - auc: 0.9203 - loss: 0.2956 - val_auc: 0.9081 - val_loss: 0.3151
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 339us/step - auc: 0.9210 - loss: 0.2945 - val_auc: 0.9082 - val_loss: 0.3149
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 335us/step - auc: 0.9216 - loss: 0.2934 - val_auc: 0.9085 - val_loss: 0.3148
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 337us/step - auc: 0.9222 - loss: 0.2924 - val_auc: 0.9084 - val_loss: 0.3149
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 336us/step - auc: 0.9228 - loss: 0.2914 - val_auc: 0.9086 - val_loss: 0.3148
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - auc: 0.9233 - loss: 0.2905 - val_auc: 0.9087 - val_loss: 0.3148
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 242us/step - auc: 0.9076 - loss: 0.3171

In [32]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 184us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.9077

## 3 hidden layers, Funnel

In [ ]:
#construct the model
inputs = keras.Input(shape=(102,)) #102 inputs, input layer
x = layers.Dense(128, activation='relu')(inputs) #hidden layer 1
x = layers.Dense(64, activation='relu')(x) #hidden layer 2
x = layers.Dense(32, activation='relu')(x) #hidden layer 3
outputs = layers.Dense(1, activation='sigmoid')(x) #output layer (sigmoid for binary outcome)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_model_funnel3")

In [34]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 512us/step - auc: 0.8865 - loss: 0.3471 - val_auc: 0.8967 - val_loss: 0.3328
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 507us/step - auc: 0.9039 - loss: 0.3222 - val_auc: 0.9008 - val_loss: 0.3261
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 423us/step - auc: 0.9093 - loss: 0.3134 - val_auc: 0.9032 - val_loss: 0.3225
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - auc: 0.9136 - loss: 0.3064 - val_auc: 0.9043 - val_loss: 0.3214
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - auc: 0.9171 - loss: 0.3005 - val_auc: 0.9049 - val_loss: 0.3211
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - auc: 0.9204 - loss: 0.2950 - val_auc: 0.9047 - val_loss: 0.3226
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - auc: 0.9230 - loss: 0.2904 - val_auc: 0.9042 - val_loss: 0.3249
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - auc: 0.9254 - loss: 0.2860 - val_auc: 0.9032 - val_loss: 0.3291
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - auc: 0.9279 - loss: 0.2815 - val_auc: 0.9025 - val_loss: 0.3325
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - auc: 0.9301 - loss: 0.2772 - val_auc: 0.9013 - val_loss: 0.3363
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - auc: 0.9321 - loss: 0.2732 - val_auc: 0.8989 - val_loss: 0.3444
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - auc: 0.9343 - loss: 0.2691 - val_auc: 0.8962 - val_loss: 0.3526
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - auc: 0.9359 - loss: 0.2657 - val_auc: 0.8942 - val_loss: 0.3595
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - auc: 0.9382 - loss: 0.2611 - val_auc: 0.8914 - val_loss: 0.3732
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - auc: 0.9393 - loss: 0.2588 - val_auc: 0.8886 - val_loss: 0.3806
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - auc: 0.9409 - loss: 0.2554 - val_auc: 0.8864 - val_loss: 0.3922
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - auc: 0.9425 - loss: 0.2522 - val_auc: 0.8850 - val_loss: 0.4082
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - auc: 0.9436 - loss: 0.2499 - val_auc: 0.8836 - val_loss: 0.4220
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - auc: 0.9445 - loss: 0.2475 - val_auc: 0.8833 - val_loss: 0.4312
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - auc: 0.9457 - loss: 0.2448 - val_auc: 0.8813 - val_loss: 0.4438
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 266us/step - auc: 0.8812 - loss: 0.4355

In [35]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.8841

## 3 hidden layers, Flat

In [48]:
#construct the model
inputs = keras.Input(shape=(102,)) #102 inputs, input layer
x = layers.Dense(64, activation='relu')(inputs) #hidden layer 1
x = layers.Dense(64, activation='relu')(x) #hidden layer 2
x = layers.Dense(64, activation='relu')(x) #hidden layer 3
outputs = layers.Dense(1, activation='sigmoid')(x) #output layer (sigmoid for binary outcome)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_model_flat3")

In [49]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 513us/step - auc: 0.8871 - loss: 0.3463 - val_auc: 0.8964 - val_loss: 0.3335
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - auc: 0.9033 - loss: 0.3231 - val_auc: 0.8999 - val_loss: 0.3277
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - auc: 0.9077 - loss: 0.3161 - val_auc: 0.9024 - val_loss: 0.3243
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - auc: 0.9114 - loss: 0.3100 - val_auc: 0.9034 - val_loss: 0.3233
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - auc: 0.9148 - loss: 0.3045 - val_auc: 0.9037 - val_loss: 0.3237
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 389us/step - auc: 0.9175 - loss: 0.3000 - val_auc: 0.9041 - val_loss: 0.3248
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - auc: 0.9199 - loss: 0.2956 - val_auc: 0.9040 - val_loss: 0.3261
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 389us/step - auc: 0.9221 - loss: 0.2915 - val_auc: 0.9040 - val_loss: 0.3270
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - auc: 0.9243 - loss: 0.2877 - val_auc: 0.9029 - val_loss: 0.3299
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 395us/step - auc: 0.9261 - loss: 0.2843 - val_auc: 0.9022 - val_loss: 0.3340
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - auc: 0.9280 - loss: 0.2807 - val_auc: 0.9015 - val_loss: 0.3403
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - auc: 0.9296 - loss: 0.2777 - val_auc: 0.8999 - val_loss: 0.3480
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 395us/step - auc: 0.9310 - loss: 0.2749 - val_auc: 0.8993 - val_loss: 0.3516
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - auc: 0.9324 - loss: 0.2720 - val_auc: 0.8986 - val_loss: 0.3611
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - auc: 0.9337 - loss: 0.2694 - val_auc: 0.8971 - val_loss: 0.3672
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - auc: 0.9348 - loss: 0.2671 - val_auc: 0.8967 - val_loss: 0.3725
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - auc: 0.9363 - loss: 0.2642 - val_auc: 0.8948 - val_loss: 0.3824
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - auc: 0.9376 - loss: 0.2616 - val_auc: 0.8942 - val_loss: 0.3858
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - auc: 0.9387 - loss: 0.2592 - val_auc: 0.8915 - val_loss: 0.3999
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - auc: 0.9400 - loss: 0.2569 - val_auc: 0.8914 - val_loss: 0.4098
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 252us/step - auc: 0.8907 - loss: 0.4011

In [50]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 221us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.8918

## 3 hidden layers, Expanding

In [45]:
#construct the model
inputs = keras.Input(shape=(102,)) #102 inputs, input layer
x = layers.Dense(32, activation='relu')(inputs) #hidden layer 1
x = layers.Dense(64, activation='relu')(x) #hidden layer 2
x = layers.Dense(128, activation='relu')(x) #hidden layer 3
outputs = layers.Dense(1, activation='sigmoid')(x) #output layer (sigmoid for binary outcome)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_model_exp3")

In [46]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 486us/step - auc: 0.8807 - loss: 0.3544 - val_auc: 0.8947 - val_loss: 0.3361
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - auc: 0.9009 - loss: 0.3268 - val_auc: 0.8980 - val_loss: 0.3310
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - auc: 0.9049 - loss: 0.3203 - val_auc: 0.9005 - val_loss: 0.3272
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - auc: 0.9082 - loss: 0.3151 - val_auc: 0.9019 - val_loss: 0.3255
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - auc: 0.9114 - loss: 0.3101 - val_auc: 0.9035 - val_loss: 0.3238
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - auc: 0.9141 - loss: 0.3056 - val_auc: 0.9040 - val_loss: 0.3237
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - auc: 0.9161 - loss: 0.3022 - val_auc: 0.9043 - val_loss: 0.3239
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - auc: 0.9179 - loss: 0.2990 - val_auc: 0.9040 - val_loss: 0.3248
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - auc: 0.9194 - loss: 0.2962 - val_auc: 0.9040 - val_loss: 0.3258
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 393us/step - auc: 0.9208 - loss: 0.2938 - val_auc: 0.9035 - val_loss: 0.3272
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - auc: 0.9222 - loss: 0.2911 - val_auc: 0.9032 - val_loss: 0.3293
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - auc: 0.9235 - loss: 0.2887 - val_auc: 0.9029 - val_loss: 0.3300
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 392us/step - auc: 0.9246 - loss: 0.2865 - val_auc: 0.9024 - val_loss: 0.3322
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - auc: 0.9258 - loss: 0.2842 - val_auc: 0.9014 - val_loss: 0.3340
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - auc: 0.9270 - loss: 0.2819 - val_auc: 0.9004 - val_loss: 0.3377
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - auc: 0.9279 - loss: 0.2801 - val_auc: 0.8997 - val_loss: 0.3407
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - auc: 0.9291 - loss: 0.2778 - val_auc: 0.8990 - val_loss: 0.3433
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - auc: 0.9303 - loss: 0.2757 - val_auc: 0.8988 - val_loss: 0.3466
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - auc: 0.9313 - loss: 0.2737 - val_auc: 0.8979 - val_loss: 0.3521
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - auc: 0.9323 - loss: 0.2717 - val_auc: 0.8974 - val_loss: 0.3545
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 251us/step - auc: 0.8929 - loss: 0.3621

In [47]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 230us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.8936

# Experiment 3: Differing dropout rates with baseline model

## No dropouts = baseline model, see results above

## Light dropout rate (0.2)

In [9]:
#construct the model
inputs = keras.Input(shape=(102,))
x = layers.Dense(64, activation='relu')(inputs)  # hidden layer 1
x = layers.Dropout(0.2)(x)                        # drop 20% of neurons
x = layers.Dense(32, activation='relu')(x)        # hidden layer 2
x = layers.Dropout(0.2)(x)                        # drop 20% of neurons
outputs = layers.Dense(1, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_dropout_02")

In [10]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 465us/step - auc: 0.8694 - loss: 0.3694 - val_auc: 0.8936 - val_loss: 0.3376
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - auc: 0.8964 - loss: 0.3339 - val_auc: 0.8972 - val_loss: 0.3333
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - auc: 0.9014 - loss: 0.3262 - val_auc: 0.9000 - val_loss: 0.3282
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - auc: 0.9051 - loss: 0.3205 - val_auc: 0.9026 - val_loss: 0.3244
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - auc: 0.9076 - loss: 0.3162 - val_auc: 0.9039 - val_loss: 0.3229
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - auc: 0.9098 - loss: 0.3128 - val_auc: 0.9053 - val_loss: 0.3205
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 467us/step - auc: 0.9114 - loss: 0.3104 - val_auc: 0.9059 - val_loss: 0.3192
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - auc: 0.9129 - loss: 0.3078 - val_auc: 0.9061 - val_loss: 0.3195
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - auc: 0.9141 - loss: 0.3059 - val_auc: 0.9068 - val_loss: 0.3175
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 389us/step - auc: 0.9154 - loss: 0.3036 - val_auc: 0.9068 - val_loss: 0.3184
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - auc: 0.9158 - loss: 0.3027 - val_auc: 0.9066 - val_loss: 0.3207
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 380us/step - auc: 0.9169 - loss: 0.3009 - val_auc: 0.9073 - val_loss: 0.3186
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - auc: 0.9181 - loss: 0.2987 - val_auc: 0.9072 - val_loss: 0.3189
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - auc: 0.9187 - loss: 0.2980 - val_auc: 0.9077 - val_loss: 0.3193
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - auc: 0.9196 - loss: 0.2968 - val_auc: 0.9073 - val_loss: 0.3204
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 370us/step - auc: 0.9204 - loss: 0.2947 - val_auc: 0.9080 - val_loss: 0.3183
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - auc: 0.9207 - loss: 0.2944 - val_auc: 0.9075 - val_loss: 0.3191
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - auc: 0.9212 - loss: 0.2939 - val_auc: 0.9074 - val_loss: 0.3215
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - auc: 0.9220 - loss: 0.2923 - val_auc: 0.9071 - val_loss: 0.3218
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - auc: 0.9232 - loss: 0.2905 - val_auc: 0.9070 - val_loss: 0.3229
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 248us/step - auc: 0.9038 - loss: 0.3276

In [11]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 208us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.9040

## Heavy dropout rate (0.5)

In [12]:
inputs = keras.Input(shape=(102,))
x = layers.Dense(64, activation='relu')(inputs)  # hidden layer 1
x = layers.Dropout(0.5)(x)                        # drop 50% of neurons
x = layers.Dense(32, activation='relu')(x)        # hidden layer 2
x = layers.Dropout(0.5)(x)                        # drop 50% of neurons
outputs = layers.Dense(1, activation='sigmoid')(x)
model = keras.Model(inputs=inputs, outputs=outputs, name="adult_income_dropout_05")

In [13]:
#defines loss, optimizer, metric, and fits model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[keras.metrics.AUC(name='auc')]
)

history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

scores = model.evaluate(X_test, y_test, verbose = 1)

Epoch 1/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 1s 494us/step - auc: 0.8467 - loss: 0.3971 - val_auc: 0.8912 - val_loss: 0.3421
Epoch 2/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - auc: 0.8867 - loss: 0.3504 - val_auc: 0.8956 - val_loss: 0.3356
Epoch 3/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - auc: 0.8927 - loss: 0.3420 - val_auc: 0.8981 - val_loss: 0.3322
Epoch 4/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - auc: 0.8948 - loss: 0.3384 - val_auc: 0.8998 - val_loss: 0.3291
Epoch 5/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - auc: 0.8983 - loss: 0.3330 - val_auc: 0.9015 - val_loss: 0.3266
Epoch 6/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - auc: 0.8999 - loss: 0.3296 - val_auc: 0.9015 - val_loss: 0.3258
Epoch 7/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - auc: 0.9012 - loss: 0.3279 - val_auc: 0.9030 - val_loss: 0.3242
Epoch 8/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 394us/step - auc: 0.9040 - loss: 0.3242 - val_auc: 0.9033 - val_loss: 0.3231
Epoch 9/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - auc: 0.9042 - loss: 0.3230 - val_auc: 0.9039 - val_loss: 0.3224
Epoch 10/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - auc: 0.9053 - loss: 0.3224 - val_auc: 0.9052 - val_loss: 0.3209
Epoch 11/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - auc: 0.9078 - loss: 0.3172 - val_auc: 0.9050 - val_loss: 0.3211
Epoch 12/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - auc: 0.9050 - loss: 0.3227 - val_auc: 0.9066 - val_loss: 0.3198
Epoch 13/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - auc: 0.9082 - loss: 0.3178 - val_auc: 0.9072 - val_loss: 0.3175
Epoch 14/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - auc: 0.9079 - loss: 0.3181 - val_auc: 0.9079 - val_loss: 0.3162
Epoch 15/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - auc: 0.9082 - loss: 0.3175 - val_auc: 0.9071 - val_loss: 0.3170
Epoch 16/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 373us/step - auc: 0.9104 - loss: 0.3134 - val_auc: 0.9075 - val_loss: 0.3168
Epoch 17/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 372us/step - auc: 0.9099 - loss: 0.3144 - val_auc: 0.9073 - val_loss: 0.3182
Epoch 18/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 366us/step - auc: 0.9111 - loss: 0.3113 - val_auc: 0.9078 - val_loss: 0.3170
Epoch 19/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 371us/step - auc: 0.9105 - loss: 0.3129 - val_auc: 0.9078 - val_loss: 0.3173
Epoch 20/20
977/977 ━━━━━━━━━━━━━━━━━━━━ 0s 369us/step - auc: 0.9116 - loss: 0.3114 - val_auc: 0.9080 - val_loss: 0.3167
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 240us/step - auc: 0.9066 - loss: 0.3195

In [14]:
# evaluate the model using the test set
y_pred_prob = model.predict(X_test)
y_pred = (y_pred_prob > 0.5).astype(int)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Test Set Evaluation:") 
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 201us/step

 Test Set Evaluation:
Test ROC AUC Score: 0.9069

# Model tuning with Optuna

In [15]:
def objective(trial):
    num_layers = trial.suggest_int("num_layers", 1, 3)  # number of hidden layers
    learning_rate = trial.suggest_float("learning_rate", 1e-4, 1e-2, log=True)  # log scale for LR
    batch_size = trial.suggest_categorical("batch_size", [16, 32, 64])  # common batch sizes
    inputs = keras.Input(shape=(102,))  # 102 input features
    x = inputs

    for i in range(num_layers):
        units = trial.suggest_int(f"num_units_layer_{i+1}", 4, 128)  # neurons per layer
        x = layers.Dense(units, activation="relu")(x)  # hidden layer

    outputs = layers.Dense(1, activation='sigmoid')(x)
    model = keras.Model(inputs=inputs, outputs=outputs)  # build model

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
        loss='binary_crossentropy',
        metrics=[keras.metrics.AUC(name='auc')]
    )

    early_stop = keras.callbacks.EarlyStopping(
        monitor="val_loss",  # watch validation loss
        patience=5,  # stop after 5 epochs without improvement
        restore_best_weights=True  # keep best model weights
    )

    history = model.fit(
        X_train,
        y_train,
        batch_size=batch_size,
        epochs=75,  # max training epochs
        validation_split=0.2,  # validation portion of training data
        verbose=0,  # suppress output during tuning
        callbacks=[early_stop]  # apply early stopping
    )

    return min(history.history["val_loss"])  # objective = best validation loss


study = optuna.create_study(direction="minimize")  # minimize validation loss
study.optimize(objective, n_trials=20)  # run 20 trials (20 models)

print("Best validation loss:", study.best_value)
print("Best parameters:", study.best_params)

[I 2026-05-19 12:05:26,641] A new study created in memory with name: no-name-3f8b1d41-0450-4d9b-a27a-2a1e564d21db
[I 2026-05-19 12:05:35,807] Trial 0 finished with value: 0.3152136504650116 and parameters: {'num_layers': 1, 'learning_rate': 0.0005464046577323495, 'batch_size': 64, 'num_units_layer_1': 69}. Best is trial 0 with value: 0.3152136504650116.
[I 2026-05-19 12:05:40,501] Trial 1 finished with value: 0.31629255414009094 and parameters: {'num_layers': 3, 'learning_rate': 0.0005395008012213594, 'batch_size': 64, 'num_units_layer_1': 30, 'num_units_layer_2': 83, 'num_units_layer_3': 5}. Best is trial 0 with value: 0.3152136504650116.
[I 2026-05-19 12:05:53,865] Trial 2 finished with value: 0.31602489948272705 and parameters: {'num_layers': 2, 'learning_rate': 0.00020423175713567328, 'batch_size': 32, 'num_units_layer_1': 29, 'num_units_layer_2': 100}. Best is trial 0 with value: 0.3152136504650116.
[I 2026-05-19 12:06:10,675] Trial 3 finished with value: 0.3178706467151642 and parameters: {'num_layers': 2, 'learning_rate': 0.00013916500653451884, 'batch_size': 32, 'num_units_layer_1': 34, 'num_units_layer_2': 114}. Best is trial 0 with value: 0.3152136504650116.
[I 2026-05-19 12:06:36,025] Trial 4 finished with value: 0.3166007399559021 and parameters: {'num_layers': 1, 'learning_rate': 0.00010958072656571694, 'batch_size': 32, 'num_units_layer_1': 86}. Best is trial 0 with value: 0.3152136504650116.
[I 2026-05-19 12:06:50,657] Trial 5 finished with value: 0.3174755275249481 and parameters: {'num_layers': 2, 'learning_rate': 0.00017091740525811957, 'batch_size': 32, 'num_units_layer_1': 37, 'num_units_layer_2': 95}. Best is trial 0 with value: 0.3152136504650116.
[I 2026-05-19 12:07:04,253] Trial 6 finished with value: 0.31513285636901855 and parameters: {'num_layers': 1, 'learning_rate': 0.0004271705720796524, 'batch_size': 64, 'num_units_layer_1': 28}. Best is trial 6 with value: 0.31513285636901855.
[I 2026-05-19 12:07:11,102] Trial 7 finished with value: 0.31877657771110535 and parameters: {'num_layers': 3, 'learning_rate': 0.0002694424811330278, 'batch_size': 32, 'num_units_layer_1': 93, 'num_units_layer_2': 36, 'num_units_layer_3': 103}. Best is trial 6 with value: 0.31513285636901855.
[I 2026-05-19 12:07:18,933] Trial 8 finished with value: 0.32242539525032043 and parameters: {'num_layers': 2, 'learning_rate': 0.007727198533945636, 'batch_size': 16, 'num_units_layer_1': 112, 'num_units_layer_2': 48}. Best is trial 6 with value: 0.31513285636901855.
[I 2026-05-19 12:07:30,264] Trial 9 finished with value: 0.31653696298599243 and parameters: {'num_layers': 2, 'learning_rate': 0.00040113096445498325, 'batch_size': 16, 'num_units_layer_1': 94, 'num_units_layer_2': 10}. Best is trial 6 with value: 0.31513285636901855.
[I 2026-05-19 12:07:39,662] Trial 10 finished with value: 0.31328460574150085 and parameters: {'num_layers': 1, 'learning_rate': 0.0019704109589132714, 'batch_size': 64, 'num_units_layer_1': 8}. Best is trial 10 with value: 0.31328460574150085.
[I 2026-05-19 12:07:52,864] Trial 11 finished with value: 0.31156104803085327 and parameters: {'num_layers': 1, 'learning_rate': 0.002084513427543767, 'batch_size': 64, 'num_units_layer_1': 4}. Best is trial 11 with value: 0.31156104803085327.
[I 2026-05-19 12:08:00,258] Trial 12 finished with value: 0.312719464302063 and parameters: {'num_layers': 1, 'learning_rate': 0.0024408267652648256, 'batch_size': 64, 'num_units_layer_1': 12}. Best is trial 11 with value: 0.31156104803085327.
[I 2026-05-19 12:08:12,931] Trial 13 finished with value: 0.3125859498977661 and parameters: {'num_layers': 1, 'learning_rate': 0.002268580869031401, 'batch_size': 64, 'num_units_layer_1': 4}. Best is trial 11 with value: 0.31156104803085327.
[I 2026-05-19 12:08:16,630] Trial 14 finished with value: 0.3154542148113251 and parameters: {'num_layers': 1, 'learning_rate': 0.001870399002985399, 'batch_size': 64, 'num_units_layer_1': 52}. Best is trial 11 with value: 0.31156104803085327.
[I 2026-05-19 12:08:24,292] Trial 15 finished with value: 0.3145400881767273 and parameters: {'num_layers': 1, 'learning_rate': 0.004836373834103789, 'batch_size': 64, 'num_units_layer_1': 4}. Best is trial 11 with value: 0.31156104803085327.
[I 2026-05-19 12:08:30,193] Trial 16 finished with value: 0.3139655590057373 and parameters: {'num_layers': 1, 'learning_rate': 0.0012230686866050618, 'batch_size': 64, 'num_units_layer_1': 54}. Best is trial 11 with value: 0.31156104803085327.
[I 2026-05-19 12:08:40,249] Trial 17 finished with value: 0.3197624683380127 and parameters: {'num_layers': 3, 'learning_rate': 0.004067648385723008, 'batch_size': 16, 'num_units_layer_1': 127, 'num_units_layer_2': 4, 'num_units_layer_3': 35}. Best is trial 11 with value: 0.31156104803085327.
[I 2026-05-19 12:08:48,888] Trial 18 finished with value: 0.31715822219848633 and parameters: {'num_layers': 1, 'learning_rate': 0.0009895483673226307, 'batch_size': 64, 'num_units_layer_1': 18}. Best is trial 11 with value: 0.31156104803085327.
[I 2026-05-19 12:08:52,658] Trial 19 finished with value: 0.32073846459388733 and parameters: {'num_layers': 2, 'learning_rate': 0.0010479642437301922, 'batch_size': 64, 'num_units_layer_1': 48, 'num_units_layer_2': 126}. Best is trial 11 with value: 0.31156104803085327.

Best validation loss: 0.31156104803085327
Best parameters: {'num_layers': 1, 'learning_rate': 0.002084513427543767, 'batch_size': 64, 'num_units_layer_1': 4}

In [16]:
# Building the best model from Optuna results
best_params = study.best_params
num_layers = best_params["num_layers"]
learning_rate = best_params["learning_rate"]
batch_size = best_params["batch_size"]  
inputs = keras.Input(shape=(102,))
x = inputs
for i in range(num_layers):
    units = best_params[f"num_units_layer_{i+1}"]
    x = layers.Dense(units, activation="relu")(x)
outputs = layers.Dense(1, activation='sigmoid')(x)
best_model = keras.Model(inputs=inputs, outputs=outputs)
best_model.compile(
    loss='binary_crossentropy',
    optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
    metrics=[keras.metrics.AUC(name='auc')],
)   

history = best_model.fit(X_train, y_train, batch_size=batch_size, epochs=75, validation_split=0.2, verbose=1, callbacks=[keras.callbacks.EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)])
scores = best_model.evaluate(X_test, y_test, verbose=1)

Epoch 1/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 1s 562us/step - auc: 0.8215 - loss: 0.4218 - val_auc: 0.8874 - val_loss: 0.3492
Epoch 2/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - auc: 0.8960 - loss: 0.3352 - val_auc: 0.8928 - val_loss: 0.3396
Epoch 3/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - auc: 0.8991 - loss: 0.3298 - val_auc: 0.8948 - val_loss: 0.3360
Epoch 4/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9010 - loss: 0.3268 - val_auc: 0.8963 - val_loss: 0.3336
Epoch 5/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - auc: 0.9023 - loss: 0.3246 - val_auc: 0.8976 - val_loss: 0.3313
Epoch 6/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - auc: 0.9034 - loss: 0.3229 - val_auc: 0.8988 - val_loss: 0.3296
Epoch 7/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 377us/step - auc: 0.9043 - loss: 0.3215 - val_auc: 0.8997 - val_loss: 0.3282
Epoch 8/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 374us/step - auc: 0.9050 - loss: 0.3204 - val_auc: 0.9005 - val_loss: 0.3269
Epoch 9/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 368us/step - auc: 0.9055 - loss: 0.3195 - val_auc: 0.9010 - val_loss: 0.3260
Epoch 10/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - auc: 0.9060 - loss: 0.3187 - val_auc: 0.9015 - val_loss: 0.3252
Epoch 11/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - auc: 0.9065 - loss: 0.3181 - val_auc: 0.9019 - val_loss: 0.3247
Epoch 12/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - auc: 0.9069 - loss: 0.3175 - val_auc: 0.9022 - val_loss: 0.3242
Epoch 13/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - auc: 0.9073 - loss: 0.3170 - val_auc: 0.9024 - val_loss: 0.3238
Epoch 14/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - auc: 0.9076 - loss: 0.3165 - val_auc: 0.9026 - val_loss: 0.3234
Epoch 15/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - auc: 0.9078 - loss: 0.3161 - val_auc: 0.9029 - val_loss: 0.3230
Epoch 16/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 455us/step - auc: 0.9081 - loss: 0.3158 - val_auc: 0.9030 - val_loss: 0.3227
Epoch 17/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - auc: 0.9083 - loss: 0.3155 - val_auc: 0.9032 - val_loss: 0.3224
Epoch 18/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - auc: 0.9085 - loss: 0.3151 - val_auc: 0.9034 - val_loss: 0.3221
Epoch 19/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - auc: 0.9087 - loss: 0.3148 - val_auc: 0.9036 - val_loss: 0.3219
Epoch 20/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - auc: 0.9089 - loss: 0.3146 - val_auc: 0.9037 - val_loss: 0.3216
Epoch 21/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - auc: 0.9091 - loss: 0.3144 - val_auc: 0.9038 - val_loss: 0.3214
Epoch 22/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - auc: 0.9092 - loss: 0.3142 - val_auc: 0.9039 - val_loss: 0.3213
Epoch 23/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - auc: 0.9093 - loss: 0.3140 - val_auc: 0.9040 - val_loss: 0.3211
Epoch 24/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - auc: 0.9095 - loss: 0.3138 - val_auc: 0.9041 - val_loss: 0.3209
Epoch 25/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - auc: 0.9096 - loss: 0.3136 - val_auc: 0.9042 - val_loss: 0.3208
Epoch 26/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - auc: 0.9097 - loss: 0.3134 - val_auc: 0.9043 - val_loss: 0.3207
Epoch 27/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9098 - loss: 0.3133 - val_auc: 0.9044 - val_loss: 0.3205
Epoch 28/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - auc: 0.9099 - loss: 0.3131 - val_auc: 0.9045 - val_loss: 0.3204
Epoch 29/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - auc: 0.9101 - loss: 0.3129 - val_auc: 0.9046 - val_loss: 0.3202
Epoch 30/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - auc: 0.9101 - loss: 0.3128 - val_auc: 0.9047 - val_loss: 0.3201
Epoch 31/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - auc: 0.9102 - loss: 0.3127 - val_auc: 0.9048 - val_loss: 0.3200
Epoch 32/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - auc: 0.9103 - loss: 0.3125 - val_auc: 0.9049 - val_loss: 0.3198
Epoch 33/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - auc: 0.9104 - loss: 0.3124 - val_auc: 0.9050 - val_loss: 0.3197
Epoch 34/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - auc: 0.9105 - loss: 0.3123 - val_auc: 0.9050 - val_loss: 0.3196
Epoch 35/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - auc: 0.9105 - loss: 0.3122 - val_auc: 0.9051 - val_loss: 0.3195
Epoch 36/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - auc: 0.9106 - loss: 0.3121 - val_auc: 0.9051 - val_loss: 0.3195
Epoch 37/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 363us/step - auc: 0.9106 - loss: 0.3120 - val_auc: 0.9052 - val_loss: 0.3194
Epoch 38/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - auc: 0.9107 - loss: 0.3118 - val_auc: 0.9052 - val_loss: 0.3194
Epoch 39/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - auc: 0.9108 - loss: 0.3118 - val_auc: 0.9052 - val_loss: 0.3193
Epoch 40/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - auc: 0.9109 - loss: 0.3117 - val_auc: 0.9052 - val_loss: 0.3193
Epoch 41/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step - auc: 0.9109 - loss: 0.3116 - val_auc: 0.9053 - val_loss: 0.3193
Epoch 42/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - auc: 0.9110 - loss: 0.3115 - val_auc: 0.9052 - val_loss: 0.3193
Epoch 43/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - auc: 0.9110 - loss: 0.3114 - val_auc: 0.9053 - val_loss: 0.3193
Epoch 44/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - auc: 0.9111 - loss: 0.3114 - val_auc: 0.9053 - val_loss: 0.3194
Epoch 45/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9111 - loss: 0.3113 - val_auc: 0.9053 - val_loss: 0.3193
Epoch 46/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - auc: 0.9112 - loss: 0.3112 - val_auc: 0.9054 - val_loss: 0.3193
Epoch 47/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - auc: 0.9112 - loss: 0.3112 - val_auc: 0.9054 - val_loss: 0.3193
Epoch 48/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9112 - loss: 0.3111 - val_auc: 0.9054 - val_loss: 0.3192
Epoch 49/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - auc: 0.9112 - loss: 0.3111 - val_auc: 0.9054 - val_loss: 0.3192
Epoch 50/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - auc: 0.9113 - loss: 0.3110 - val_auc: 0.9055 - val_loss: 0.3192
Epoch 51/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - auc: 0.9113 - loss: 0.3110 - val_auc: 0.9055 - val_loss: 0.3192
Epoch 52/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - auc: 0.9113 - loss: 0.3109 - val_auc: 0.9055 - val_loss: 0.3192
Epoch 53/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - auc: 0.9114 - loss: 0.3109 - val_auc: 0.9056 - val_loss: 0.3191
Epoch 54/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - auc: 0.9114 - loss: 0.3108 - val_auc: 0.9056 - val_loss: 0.3191
Epoch 55/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - auc: 0.9114 - loss: 0.3108 - val_auc: 0.9056 - val_loss: 0.3191
Epoch 56/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - auc: 0.9114 - loss: 0.3107 - val_auc: 0.9056 - val_loss: 0.3190
Epoch 57/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9115 - loss: 0.3106 - val_auc: 0.9057 - val_loss: 0.3190
Epoch 58/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - auc: 0.9115 - loss: 0.3105 - val_auc: 0.9057 - val_loss: 0.3190
Epoch 59/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - auc: 0.9115 - loss: 0.3105 - val_auc: 0.9057 - val_loss: 0.3189
Epoch 60/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - auc: 0.9116 - loss: 0.3104 - val_auc: 0.9057 - val_loss: 0.3189
Epoch 61/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 340us/step - auc: 0.9116 - loss: 0.3104 - val_auc: 0.9057 - val_loss: 0.3189
Epoch 62/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 570us/step - auc: 0.9116 - loss: 0.3103 - val_auc: 0.9057 - val_loss: 0.3189
Epoch 63/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - auc: 0.9116 - loss: 0.3102 - val_auc: 0.9057 - val_loss: 0.3189
Epoch 64/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - auc: 0.9117 - loss: 0.3101 - val_auc: 0.9058 - val_loss: 0.3189
Epoch 65/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - auc: 0.9117 - loss: 0.3101 - val_auc: 0.9058 - val_loss: 0.3188
Epoch 66/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - auc: 0.9117 - loss: 0.3100 - val_auc: 0.9057 - val_loss: 0.3189
Epoch 67/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - auc: 0.9118 - loss: 0.3099 - val_auc: 0.9058 - val_loss: 0.3188
Epoch 68/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - auc: 0.9118 - loss: 0.3099 - val_auc: 0.9058 - val_loss: 0.3188
Epoch 69/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - auc: 0.9118 - loss: 0.3098 - val_auc: 0.9059 - val_loss: 0.3188
Epoch 70/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 340us/step - auc: 0.9118 - loss: 0.3098 - val_auc: 0.9058 - val_loss: 0.3188
Epoch 71/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - auc: 0.9119 - loss: 0.3097 - val_auc: 0.9059 - val_loss: 0.3187
Epoch 72/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - auc: 0.9119 - loss: 0.3096 - val_auc: 0.9059 - val_loss: 0.3187
Epoch 73/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 340us/step - auc: 0.9119 - loss: 0.3096 - val_auc: 0.9058 - val_loss: 0.3187
Epoch 74/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - auc: 0.9119 - loss: 0.3096 - val_auc: 0.9059 - val_loss: 0.3186
Epoch 75/75
489/489 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - auc: 0.9119 - loss: 0.3095 - val_auc: 0.9058 - val_loss: 0.3187
306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 247us/step - auc: 0.9050 - loss: 0.3210

In [18]:
# evaluate the best model using the test set
y_pred_prob = best_model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print("\n Best Model Test Set Evaluation:")
print(f"Test ROC AUC Score: {roc_auc:.4f}")

306/306 ━━━━━━━━━━━━━━━━━━━━ 0s 164us/step

 Best Model Test Set Evaluation:
Test ROC AUC Score: 0.9051